name: Node.js CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # Use the Node.js version you're using for the project

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run tests
    - name: Run tests
      run: npm test
