name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build . -t tech-challenge-fase2-app

    # Nova etapa: Instalar Docker Compose
    - name: Install Docker Compose
      run: sudo apt-get install docker-compose -y

    # Rodar Docker Compose
    - name: Run Docker Compose
      run: docker-compose up --build -d