name: Node.js CI

# Define quando o workflow será acionado
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checa o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura a versão do Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Instala as dependências
      - name: Install dependencies
        run: npm install

      # Executa os testes
      - name: Run tests
        run: npm test